// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVOtsewfAtSJgMFEFSTkYEMjSVFWwZbgQ',
    appId: '1:543985251306:android:3c640ed840c395fce27893',
    messagingSenderId: '543985251306',
    projectId: 'blcaproject',
    storageBucket: 'blcaproject.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVa9D3XHSXS_CB0olZwtxsYeFClZDCFYU',
    appId: '1:543985251306:web:babed471e177a02ae27893',
    messagingSenderId: '543985251306',
    projectId: 'blcaproject',
    authDomain: 'blcaproject.firebaseapp.com',
    storageBucket: 'blcaproject.appspot.com',
    measurementId: 'G-XZT13999F7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBihK0OYw3_mdtx9kqjeKqtDVnp0rwg5U4',
    appId: '1:543985251306:ios:7d156c8e2d50c6e9e27893',
    messagingSenderId: '543985251306',
    projectId: 'blcaproject',
    storageBucket: 'blcaproject.appspot.com',
    iosBundleId: 'com.example.blcaProjectApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBihK0OYw3_mdtx9kqjeKqtDVnp0rwg5U4',
    appId: '1:543985251306:ios:7d156c8e2d50c6e9e27893',
    messagingSenderId: '543985251306',
    projectId: 'blcaproject',
    storageBucket: 'blcaproject.appspot.com',
    iosBundleId: 'com.example.blcaProjectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVa9D3XHSXS_CB0olZwtxsYeFClZDCFYU',
    appId: '1:543985251306:web:e200ce918e10a0cce27893',
    messagingSenderId: '543985251306',
    projectId: 'blcaproject',
    authDomain: 'blcaproject.firebaseapp.com',
    storageBucket: 'blcaproject.appspot.com',
    measurementId: 'G-01TB5EHV5H',
  );

}